Story_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls'))
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.index, name='index'),
]

landingpage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    post_time = models.DateTimeField(auto_now_add=True)
    status = models.TextField()

landingpage/forms.py
from django import forms

class Status_form(forms.Form):
    statusInput = {'id': 'forms', 'name' : 'status'}

    status = forms.CharField(label='Status',required=True, initial="Say how you feel", widget=forms.Textarea(statusInput))

landingpage/views.py
from django.shortcuts import render
from .forms import Status_form
from .models import Status

# Create your views here.

def index(request):
    status_list = Status.objects.all()
    if request.method == 'POST':
        blank_form = Status_form()
        filled_form = Status_form(request.POST)
        if filled_form.is_valid():
            status = Status(status = filled_form.data['status'])
            status.save()
            form = {'form':blank_form, 'status_list':status_list}
            return render(request, 'index.html', form)

    else:
        blank_form = Status_form()
        form = {'form':blank_form, 'status_list':status_list}
        return render(request, 'index.html', form)

    

landingpage/templates/index.html
<!DOCTYPE html>
{% load static %}
<head>

</head>
<body>
    <h1>Hello, How are you?</h1>
    <form action="{% url 'landingpage:index' %}" method="POST">
        {% csrf_token %}
        <p>Say what's on your mind</p>
        {{ form.status }}
        <input type="submit" value="post">
    </form>
    <ul>
        {% for stats in status_list %}
        <li>
            {{ stats.status}}
        </li>
        {% endfor %}
    </ul>

</body>